name: DipSA CICD Workshop

#trigger
on:
 push:
  branches:
  - 'v[0-9]+.[0-9]+'
  #Step-1
  #test this on 3- release with branch name

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:

    - name: echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"

    - name: Get deployment URL
      id: deployment
      uses: dorshinar/get-deployment-url@master
      timeout-minutes: 1
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nJason Tay Neng Wei"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA0265092A"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\nJason.Tay.NW@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n${{ steps.deployment.outputs.deployment }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "<${{ steps.deployment.outputs.deployment }}|Open Application>"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#wonder what mrkdwn means- markdown?

    # - name: Send custom JSON data to Slack workflow
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.23.0
    #   with:
    #     # For posting a rich message using Block Kit
    #     payload: |
    #       {
    #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} || toJSON(github.event.head_commit.message)",
    #         "blocks": [
    #           {
    #             "type": "section",
    #             "text": {
    #               "type": "mrkdwn",
    #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    #             }
    #           }
    #         ]
    #       }
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
    #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



    # - name: deploy to vercel
    #   uses: amondnet/vercel-action@v25.1.0
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     github-token: ${{ secrets.GH_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJ_ID }}
    #     vercel-args: '--prod'