name: DipSA CICD Workshop

#trigger
on:
 push:
  branches:
  - 'v[0-9]+.[0-9]+'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/release'
    steps:
    - name: echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"

    - name: checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        
    - name: deploy to vercel
      uses: amondnet/vercel-action@v25.1.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GH_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJ_ID }}
        vercel-args: '--prod'