name: DipSA CICD Workshop

#trigger
on:
 push:
  branches:
  - 'v[0-9]+.[0-9]+'
  #Step-1
  #test this on 3- release with branch name

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:

    - name: echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": 
            [
            {
              "type": "section",
              "text": 
              {
              "type": "mrkdwn",
              "text": "Name: 
              something someone
              Email:
              tttttt6@u.nus.edu
              Deployment:
              https://test"
              }
            }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


    # - name: Send custom JSON data to Slack workflow
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.23.0
    #   with:
    #     # For posting a rich message using Block Kit
    #     payload: |
    #       {
    #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
    #         "blocks": [
    #           {
    #             "type": "section",
    #             "text": {
    #               "type": "mrkdwn",
    #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    #             }
    #           }
    #         ]
    #       }
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST }}
    #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



    # - name: deploy to vercel
    #   uses: amondnet/vercel-action@v25.1.0
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     github-token: ${{ secrets.GH_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJ_ID }}
    #     vercel-args: '--prod'